### ISSUE TITLE
suggestion: Empty string case for input -> refresh conversation

### ISSUE THREAD

**Issue by mihilt** [noook/igdm-cli#13]
i also found same issue with #6
and i want to suggest one of solution

add `case '':` to line 97 line in `direct-messaging.ts` file promt function can definitely make what he want

i think it is better to add it in 98 line tho
cuz i use \r more :)

**Comment by noook** [comment]
Hello ! Great to hear you use this !
And I agree with you, I think it's more common to refresh then go back to conversation list.

However, now that I know how people use it, it would be great to find a shortcut to go back to the conversation as well.

Feel free to contribute if you find time, otherwise I can add it myself.
